
# COOLDOWNS
# Set to true to disable cooldowns
disable_cooldowns: false

# Cooldown time per stone in ms
# Water stone
water_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  waterbending_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  ice_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000

# Fire stone
fire_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  hellfire_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  explosion_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000

# Air stone
air_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  agility_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  airbending_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000

# Earth stone
earth_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  earthbending_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  lava_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000



# DROP CHANCE
# Set to one ensure drop
# The higher the number, the lower the drop chance (formula: 1/x)
drop_chance:
  baby_zombie_hide: 10
  rotten_apple: 10
  insect: 10
  bat: 10
  herb: 10
  golden_feather: 10
  dead_flower: 10
  twig: 10
  soul_of_evoker: 10
  villager_blood: 10

  # Drop chance for a spell when a shaman reaches level 5
  spell: 2



# XP VALUE
xp_value:
  # Base items
  baby_zombie_hide: 10
  rotten_apple: 10
  insect: 10
  bat: 10
  thyme: 10
  oregano: 10
  dill: 10
  rosemary: 7
  golden_feather: 10
  dead_flower: 10
  twig: 10
  soul_of_evoker: 10
  blood_of_wandering_trader: 10
  stinger: 10
  hoglin_tusk: 10
  finn: 10

  # Craft items
  voodoo_doll: 20
  ship_in_bottle: 20
  palantir: 20
  blood_and_quil: 20
  bundle_of_herbs: 20
  carnivorous_plant: 20
  scented_candle: 20
  finn_soup: 20
  war_horn: 20
  poisonous_dart: 20
  broom: 20
  poisoned_apple: 20
  mystery_potion: 20
  antidote: 20
  gingerbread_man: 20


















