
# COOLDOWNS
# Set to true to disable cooldowns
disable_cooldowns: false

# Cooldown time per stone in ms
# Water stone
water_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  waterbending_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  ice_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000

# Fire stone
fire_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  hellfire_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  lava_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000

# Air stone
air_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  agility_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  airbending_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000

# Earth stone
earth_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  earthbending_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000
  defense_stone:
    move4: 10000
    move5: 10000
    move6: 10000
    move7: 10000
    move8: 10000



# DROP CHANCE
# Set to one ensure drop
drop_chance:
  baby_zombie_hide: 10
  rotten_apple: 10
  insect: 10
  bat: 10
  herb: 10
  golden_feather: 10
  dead_flower: 10
  twig: 10
  soul_of_evoker: 10
  villager_blood: 10