# RESOURCE PACK URL
resource_pack: "https://www.dropbox.com/s/j5gocausrog4ekz/ElementalStones.zip?dl=1"

# COOLDOWNS
# Set to true to disable cooldowns
disable_cooldowns: false

# Cooldown time per stone in ms
# Water stone
water_stone:
  default:
    move1: 5000
    move2: 30000
    move3: 10000
  waterbending_stone:
    move4: 20000
    move5: 60000
    move6: 60000
    move7: 30000
    move8: 120000
  ice_stone:
    move4: 0
    move5: 15000
    move6: 20000
    move7: 30000
    move8: 60000

# Fire stone
fire_stone:
  default:
    move1: 10000
    move2: 10000
    move3: 10000
  hellfire_stone:
    move4: 20000
    move5: 15000
    move6: 30000
    move7: 20000
    move8: 180000
  explosion_stone:
    move4: 20000
    move5: 5000
    move6: 20000
    move7: 10000
    move8: 120000

# Air stone
air_stone:
  default:
    move1: 2000
    move2: 15000
    move3: 5000
  agility_stone:
    move4: 1000
    move5: 10000
    move6: 20000
    move7: 5000
    move8: 60000
  airbending_stone:
    move4: 10000
    move5: 8000
    move6: 30000
    move7: 10000
    move8: 60000

# Earth stone
earth_stone:
  default:
    move1: 2000
    move2: 10000
    move3: 5000
  earthbending_stone:
    move4: 8000
    move5: 4000
    move6: 2000
    move7: 10000
    move8: 60000
  lava_stone:
    move4: 5000
    move5: 10000
    move6: 20000
    move7: 10000
    move8: 24000



# DROP CHANCE
# Set to one ensure drop
# The higher the number, the lower the drop chance (formula: 1/x)
drop_chance:
  baby_zombie_hide: 4
  rotten_apple: 20
  insect: 2
  bat: 4
  herb: 20
  golden_feather: 10
  dead_flower: 20
  twig: 1
  soul_of_evoker: 2
  blood_of_wandering_trader: 4
  stinger: 5
  hoglin_tusk: 10
  finn: 4

  # Drop chance for a spell when a shaman reaches level 5
  spell: 2



# XP VALUE
xp_value:
  # Base items
  baby_zombie_hide: 1
  rotten_apple: 1
  insect: 1
  bat: 1
  golden_feather: 1
  dead_flower: 1
  twig: 2
  soul_of_evoker: 3
  blood_of_wandering_trader: 2
  stinger: 1
  hoglin_tusk: 1
  finn: 1

  # Craft items
  voodoo_doll: 6
  ship_in_bottle: 2
  palantir: 4
  blood_and_quil: 4
  bundle_of_herbs: 3
  carnivorous_plant: 4
  scented_candle: 3
  finn_soup: 4
  war_horn: 4
  poisonous_dart: 4
  broom: 3
  poisoned_apple: 3
  gingerbread_man: 2


















