name: ElementalStones
version: ${project.version}
main: com.lennertsoffers.elementalstones.ElementalStones
api-version: 1.16
authors: [ lennertsoffers ]
description: A Minecraft Spigot plugin to add elemental stones to your server
commands:
  r:
    description: Reloads the server
    usage: /r
  givestone:
    description: Gives particular stone to the selected player, if none selected, the executing player gets the itemstack
    usage: /giveStone <player> <stone>
  stoneInventory:
    description: Opens inventory where you can pick a stone from, Magic Stone is default
    usage: /stoneInventory <water-fire-air-earth-magic>
  giveItem:
    description: Gives you the Rosemary Itemstack
  shamanMajor:
    description: Spawns in a shaman major
  saveDefaultConfig:
    description: Saves the default config file
  spawnCows:
    description: Spawns 100 cows
  customModelData:
    description: Sends message to the player with the custom model data of the itemstack he's holding