name: Build and release .jar file

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, package and upload .jar artifact
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build and package project
        run: mvn -f pom.xml clean package
      - uses: actions/create-release@v1
        name: Create a release on GitHub
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version 1.0 (unfinished product)
      - uses: csexton/release-asset-action@v2
        name: Upload the jar to the release
        with:
          github-token: ${{ secrets.TOKEN }}
          pattern: target/ElementalStones-1.0-SNAPSHOT.jar
          release-url: ${{ steps.create_release.outputs.upload_url }}